version: "3"
services:
  node:
    image: "node:8"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    expose:
      - "80"
    command: ['npm', 'run', 'start']
    # entrypoint: [ls]
    # entrypoint: [ls, '/usr/src/app']
    
    # command: npm run serve
   